import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:untitled/data/models/event_models.dart';

class EventsViewModel extends ChangeNotifier {
  List<Data>? _events;

  List<Data>? get events => _events;

  Future<void> fetchEvents() async {
    var headers = {
      'Accept': 'application/json',
      'Authorization': 'Bearer 2f68dbbf-519d-4f01-9636-e2421b68f379'
    };
    var request = http.Request('GET',
        Uri.parse('https://mock.apidog.com/m1/561191-524377-default/Event'));
    request.headers.addAll(headers);

    http.StreamedResponse response = await request.send();

    if (response.statusCode == 200) {
      String jsonString = await response.stream.bytesToString();
      Map<String, dynamic> jsonData = json.decode(jsonString);
      _events = Autogenerated.fromJson(jsonData).data;
      notifyListeners();
    } else {
      throw Exception(response.reasonPhrase);
    }
  }
}
